/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed-dim": "#c0c1ff",
              "on-tertiary-fixed-variant": "#6900b3",
              "secondary": "#4cd7f6",
              "error": "#ffb4ab",
              "error-container": "#93000a",
              "on-primary-fixed-variant": "#2f2ebe",
              "on-error-container": "#ffdad6",
              "surface-bright": "#31394d",
              "primary-container": "#8083ff",
              "primary": "#c0c1ff",
              "surface-container": "#171f33",
              "outline-variant": "#464554",
              "surface-variant": "#2d3449",
              "on-secondary-fixed": "#001f26",
              "on-surface": "#dae2fd",
              "surface-container-low": "#131b2e",
              "surface-container-high": "#222a3d",
              "background": "#0b1326",
              "inverse-primary": "#494bd6",
              "on-background": "#dae2fd",
              "secondary-container": "#03b5d3",
              "on-secondary-fixed-variant": "#004e5c",
              "secondary-fixed": "#acedff",
              "outline": "#908fa0",
              "secondary-fixed-dim": "#4cd7f6",
              "on-tertiary-container": "#400071",
              "inverse-surface": "#dae2fd",
              "tertiary": "#ddb7ff",
              "surface": "#0b1326",
              "tertiary-container": "#b76dff",
              "on-primary-container": "#0d0096",
              "on-surface-variant": "#c7c4d7",
              "on-error": "#690005",
              "primary-fixed": "#e1e0ff",
              "on-primary-fixed": "#07006c",
              "inverse-on-surface": "#283044",
              "tertiary-fixed-dim": "#ddb7ff",
              "surface-tint": "#c0c1ff",
              "on-tertiary": "#490080",
              "on-tertiary-fixed": "#2c0051",
              "on-secondary": "#003640",
              "surface-container-highest": "#2d3449",
              "on-primary": "#1000a9",
              "tertiary-fixed": "#f0dbff",
              "surface-dim": "#0b1326",
              "on-secondary-container": "#00424e",
              "surface-container-lowest": "#060e20"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "label-sm": ["Plus Jakarta Sans", "sans-serif"],
              "body-md": ["Plus Jakarta Sans", "sans-serif"],
              "headline-md": ["Plus Jakarta Sans", "sans-serif"],
              "body-lg": ["Plus Jakarta Sans", "sans-serif"],
              "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
              "display": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
              "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [],
}
